version: "2"

services:

  contracts:
    build: .
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - steedos-storage-1:/srv/steedos

volumes:
  # Storage for attachments
  steedos-storage-1: