version: "2"

services:

  steedos:
    build: .
    restart: unless-stopped
    ports:
      - "5040:5000"
    volumes:
      - steedos-storage-1:/storage



volumes:
  # Storage for attachments
  steedos-storage-1:/srv/workflow/cfs