version: "2"

services:

  contracts:
    build: .
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - "/srv/steedos-contracts-app/storage:/contracts/storage"
      - "./steedos-config.yml:/contracts/steedos-config.yml"