version: "2"

services:

  steedos:
    build: .
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - steedos-storage-1:/storage
    links:
      - mongo:mongo

  mongo:
    image: mongo:3.4.1
    ports:
      - "27017:27017"
    volumes:
      - mongo-db-1:/data/db
      - mongo-backup-1:/data/backup
    command: mongod --profile=1 --slowms=500 --replSet "rs0"
    restart: always

  mongo-init-replica:
    image: mongo:3.4.1
    command: 'mongo mongo/steedos --eval "rs.initiate({ _id: ''rs0'', members: [ { _id: 0, host: ''127.0.0.1:27017'' } ]})"'
    links:
      - mongo:mongo

volumes:
  # Storage for attachments
  steedos-storage-1:
  mongo-db-1:
  mongo-backup-1: