version: "2"

services:

  steedos:
    build: .
    #restart: unless-stopped
    ports:
      - "5040:5040"
    volumes:
      - /srv/workflow/cfs:/storage
      - /srv/git/steedos-contracts-app/steedos-config.yml:/app/steedos-config.yml

