env:
  PORT: 5000
  ROOT_URL: https://qhd-beta.steedos.com/contract/
datasources:
  default:
    connection:
      url: mongodb://192.168.0.21/steedos_cn
public:
  cfs:
    store: "local"
    local:
      folder: "/storage"
  webservices:
    workflow:
      url: "https://qhd-beta.steedos.com/"
cron:
  instancerecordqueue_interval: 10000
plugins: ["@steedos/plugin-jsreport"]