env:
  PORT: 5000
datasources:
  default:
    connection: 
      url: mongodb://192.168.0.21/steedos
  mongo:
    connection: 
      driver: mongo
      host: 192.168.0.21
      database: steedos
    objectFiles: 
      - "./src"
    appFiles:
      - "./src/contract.app.yml"
public:
  cfs:
    store: "local"
    local: 
      folder: "/srv/steedos"