env:
  PORT: 5000
  ROOT_URL: http://127.0.0.1:5000/
datasources:
  default:
    connection:
      url: mongodb://127.0.0.1/steedos
    objectFiles: 
      - "./src/**"
public:
  cfs:
    store: "local"

cfs:
  local:
    folder: ./storage
  aliyun:
    region:
    internal: false,
    bucket:
    folder:
    accessKeyId:
    secretAccessKey:
  aws:
    region:
    bucket:
    folder:
    accessKeyId:
    secretAccessKey:

cron:
  instancerecordqueue_interval: 10000

plugins: