datasources:
  default:
    connection:
      url: ${MONGO_URL}
    objectFiles:
      - "./src/**"
    appFiles:
      - "./src/**"
public:
  cfs:
    store: ${ENV_CFS_STORE}
  webservices:
    workflow:
      url: ${ENV_WORKFLOW_URL}
    creator:
      url: ${ENV_CREATOR_URL}
  is_group_company: true
  accounts:
    loginExpirationInDays: 1825
cfs:
  aliyun:
    region: ${ENV_CFS_ALIYUN_REGION}
    bucket: ${ENV_CFS_ALIYUN_BUCKET}
    accessKeyId: ${ENV_CFS_ALIYUN_ACCESSKEYID}
    secretAccessKey: ${ENV_CFS_ALIYUN_SECRETACCESSKEY}
