datasources:
  default:
    connection:
      url: ${MONGO_URL}
    objectFiles: 
      - "./src/**"
public:
  cfs:
    store: "local"

cfs:
  local:
    folder: ./storage

plugins:
  - "@steedos/accounts"
