env:
  PORT: 5000
datasources:
  default:
    connection: 
      url: mongodb://127.0.0.1/steedos
  mongo:
    connection: 
      driver: mongo
      host: 127.0.0.1
      database: steedos
    objectFiles: 
      - "./src"
    appFiles:
      - "./src/contract.app.yml"
public:
  cfs:
    store: "local"
    local: 
      folder: "./storage"