env:
  PORT: 5000
  ROOT_URL: https://qhd-beta.steedos.com/contract/
datasources:
  default:
    connection:
      url: mongodb://192.1.1.42/steedos
    objectFiles:
      - "./src"
    appFiles:
      - "./src/contract.app.yml"
public:
  cfs:
    store: "local"
    local:
      folder: "/srv/steedos"
  webservices:
    workflow:
      url: "https://qhd-beta.steedos.com/"
cron:
  instancerecordqueue_interval: 10000